---
- name: install packages for 389ds server
  apt:
    name:
      - "389-ds"
      - "389-admin"
      - "389-admin-console"
      - "python3-lib389"
    state: "present"

- name: generate instance setup file
  template:
    src: "{{ ds_instance_inf_src }}"
    dest: "{{ ds_instance_inf_dest }}"
    owner: root
    group: root
    mode: 0600

- name: set up and configure 389ds
  command: setup-ds-admin -s -f "{{ ds_instance_inf_dest }}"

- name: create a systemctl symlink for lib389
  file:
    src: "/bin/systemctl"
    dest: "/usr/bin/systemctl"
    state: link

- name: add a dsrc file for the root user
  template:
    src: "dsrc"
    dest: "/root/.dsrc"
    owner: "root"
    group: "root"
    mode: 0600
