---
- name: install necessary packages to build mirrors
  apt:
    name:
      - apt-mirror
    state: present

- name: configure apt-mirror
  template:
    src: mirror.list.j2
    dest: /etc/apt/mirror.list

- name: ensure offline cache directories exist
  file:
    name: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
  - "{{ offline_cache_dir }}"
  - "{{ offline_cache_dir }}/misc-files"
  - "{{ offline_cache_dir }}/docker-images"
  - "{{ offline_cache_dir }}/apt"
  - "{{ offline_cache_dir }}/apt/gpgkeys"
  - "{{ offline_cache_dir }}/apt/mirror"
  - "{{ offline_cache_dir }}/apt/skel"
  - "{{ offline_cache_dir }}/apt/var"
  - "{{ offline_cache_dir }}/pip"

- name: mirror apt repositories
  command: apt-mirror
  when: download_apt_repos

- name: download Ubuntu ISO
  get_url:
    url: "{{ ubuntu_iso_mirror }}/{{ ubuntu_iso }}"
    dest: "{{ offline_cache_dir }}/apt/{{ ubuntu_iso }}"
    mode: 0644
  when: download_apt_repos

- name: copy gpg keys to cache dir
  get_url:
    url: "{{ item.url }}"
    dest: "{{ offline_cache_dir }}/apt/gpgkeys/{{ item.name }}.pub"
    mode: "0644"
  with_items: "{{ apt_repo_gpg_keys }}"
  when: download_apt_repos

- name: clone fresh deepops repo
  git:
    repo: "https://github.com/NVIDIA/deepops"
    dest: "{{ offline_cache_dir }}/deepops"
    recursive: yes
    update: yes
    version: "master"
  when: download_deepops_repo

- name: ensure pip is installed
  apt:
    name:
    - "python3-pip"
    - "python-pip"
    state: present

- name: force up to date pip packages for downloads
  pip:
    name: "{{ item }}"
    state: "latest"
  with_items:
  - "setuptools"
  - "pip"
  when: download_pip_packages

- name: install ansible
  pip:
    name: "ansible"
    version: "{{ ansible_version }}"
    state: "present"

- name: install Ansible Galaxy dependencies in repo
  command: ansible-galaxy install -p "{{ offline_cache_dir }}/deepops/roles/galaxy" -r "{{ offline_cache_dir }}/deepops/roles/requirements.yml"
  tags:
  - skip_ansible_lint

- name: download docker compose
  get_url:
    url: "{{ docker_compose_url }}"
    dest: "{{ offline_cache_dir }}/misc-files/docker-compose"

- name: download nvidia-docker wrapper script
  get_url:
    url: "{{ nvidia_docker_wrapper_url }}"
    dest: "{{ offline_cache_dir }}/misc-files/nvidia-docker"
 
- name: install docker tools
  pip:
    name: "docker"
    state: "present"

- name: archive docker images
  docker_image:
    name: "{{ item.repo }}{{ item.image }}"
    tag: "{{ item.version }}"
    archive_path: "{{ offline_cache_dir }}/docker-images/{{ item.name }}-{{ item.version }}.tar"
    http_timeout: "{{ docker_http_timeout }}"
    timeout: "{{ docker_http_timeout }}"
    state: present
  with_items: "{{ docker_image_list }}"
  when: download_docker_images

- name: download python3 packages
  command: "pip3 download --dest {{ offline_cache_dir }}/pip {{ item.name }}"
  with_items: "{{ pip_package_list }}"
  when: download_pip_packages

- name: download slurm tarballs
  get_url:
    url: "{{ item }}"
    dest: "{{ offline_cache_dir }}/misc-files/"
    mode: 0644
  with_items:
  - "{{ slurm_src_url }}"
  - "{{ hwloc_src_url }}"
  - "{{ pmix_src_url }}"


