---
- name: install rootless buildah dependencies
  package: 
    name: "{{ item }}"
    state: present
  with_items: "{{ buildah_rpm_deps }}"
  
- name: configure kubic repo
  yum_repository:
    name: "{{ buildah_rpm_repo_name }}"
    description: "{{ buildah_rpm_repo_description }}"
    baseurl: "{{ buildah_rpm_repo }}"
    gpgkey: "{{ buildah_rpm_gpgkey }}"
    gpgcheck: true
    enabled: true

- name: install buildah
  package:
    name: "{{ buildah_rpm_pkg_name }}"
    state: present

- name: check if kernel unpriv enabled
  shell: "cat /proc/cmdline | grep 'namespace.unpriv_enable=1'"
  register: kernel_unpriv_enable
  failed_when: kernel_unpriv_enable.rc == 127

- name: check if user namespaces enabled
  shell: "cat /proc/cmdline | grep 'user_namespace.enable=1'"
  register: kernel_user_namespace
  failed_when: kernel_user_namespace.rc == 127

- name: install grubby if needed
  yum:
    name: "grubby"
    state: "present"
  when: ((kernel_unpriv_enable.rc == 1) or (kernel_user_namespace.rc == 1)) and buildah_configure_kernel_options

- name: add kernel options to use enroot
  command: "grubby --update-kernel={{ buildah_configure_kernel_options_versions }} --args={{ item }}"
  when: ((kernel_unpriv_enable.rc == 1) or (kernel_user_namespace.rc == 1)) and buildah_configure_kernel_options
  with_items:
    - "namespace.unpriv_enable=1"
    - "user_namespace.enable=1"
  notify:
  - reboot node

- name: set max_user_namespaces 
  sysctl:
    name: user.max_user_namespaces
    value: "{{ buildah_max_user_namespaces }}"
    state: present

- name: set max_mnt_namespaces
  sysctl:
    name: user.max_mnt_namespaces
    value: "{{ buildah_max_mnt_namespaces }}"
    state: present

- name: set subuid mapping
  lineinfile:
    path: "/etc/subuid"
    regexp: "^{{ item.name }}"
    line: "{{ item.name }}:{{ item.uids }}"
  with_items: "{{ buildah_mapped_users }}"

- name: set subgid mapping
  lineinfile:
    path: "/etc/subgid"
    regexp: "^{{ item.name }}"
    line: "{{ item.name }}:{{ item.gids }}"
  with_items: "{{ buildah_mapped_users }}"
