prometheus:
  ingress:
    enabled: true
  nodeSelector:
    node-role.kubernetes.io/master: ""
  serviceMonitors:
  - name: dcgm-exporter
    selector:
      matchLabels:
        app: dcgm-exporter
    endpoints:
    - port: scrape
      interval: 1s
      honorLabels: true       
  serviceMonitorsSelector:
    matchLabels:
      prometheus: "kube-prometheus"

alertmanager:
  ingress:
    enabled: true
  nodeSelector:
    node-role.kubernetes.io/master: ""

grafana:
  ingress:
    enabled: true
  nodeSelector:
    node-role.kubernetes.io/master: ""
  serverDashboardConfigmaps:
    - kube-prometheus-grafana-gpu
