---
- hosts: all
  become: yes
  tasks:

  - name: clear out base CentOS repos
    file:
      name: "{{ item }}"
      state: "absent"
    with_items:
    - "/etc/yum.repos.d/CentOS-Base.repo"
    - "/etc/yum.repos.d/CentOS-CR.repo"
    - "/etc/yum.repos.d/CentOS-Debuginfo.repo"
    - "/etc/yum.repos.d/CentOS-Media.repo"
    - "/etc/yum.repos.d/CentOS-Sources.repo"
    - "/etc/yum.repos.d/CentOS-Vault.repo"
    - "/etc/yum.repos.d/CentOS-fasttrack.repo"

  - name: configure mirror urls for base RHEL/CentOS repos
    yum_repository:
      name: "{{ item.name }}"
      description: "{{ item.name }}"
      baseurl: "{{ item.url }}"
      gpgcheck: false
    with_items: "{{ yum_base_repos }}"
