---
- hosts: all
  become: yes
  tasks:
  - name: configure mirror urls for base RHEL/CentOS repos
    yum_repository:
      name: "{{ item.name }}"
      baseurl: "{{ item.url }}"
      gpgcheck: false
    with_items: "{{ yum_base_repos }}"
