---
- hosts: all
  become: yes
  tasks:
  - name: apt update on ubuntu
    apt:
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  - name: ensure gpg is installed
    apt:
      name: "gpg-agent"
      state: present
    when: ansible_distribution == "Ubuntu"
